package com.bjpowernode.mapper.user;

import com.bjpowernode.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int updateByPrimaryKey(User record);

    /**
     * 查询用户的数量
     * @return
     */
    Integer selectAllUserCount();

    /**
     * 查询用户信息根据手机号
     * @return
     */
    User selectUserInfoByPhone(String phone);
}