package com.bjpowernode.mapper.loan;

import com.bjpowernode.model.BidInfo;
import com.bjpowernode.vo.UserRecentBidVO;

import java.util.List;
import java.util.Map;

public interface BidInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int insert(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int insertSelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    BidInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int updateByPrimaryKey(BidInfo record);

    Double selectAllBidMoney();

    List<BidInfo> selectRecentlyBidInfoByLoanId(Map<String,Object> paramMap);

    List<UserRecentBidVO> selectRecentlyBidInfoByUserId(Map<String, Object> paramMapRecentBid);

    Integer selectAllBidCountByUid(Map<String, Object> paramMap);

    List<BidInfo> selectAllBidByLoanId(Integer loanInfoId);
}