package com.bjpowernode.mapper.loan;

import com.bjpowernode.model.IncomeRecord;
import com.bjpowernode.vo.IncomeRecordVO;

import java.util.List;
import java.util.Map;

public interface IncomeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int insert(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int insertSelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    IncomeRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int updateByPrimaryKey(IncomeRecord record);

    List<IncomeRecordVO> selectIncomeRecordByUid(Map<String, Object> paramMapIncomeRecord);

    Integer selectAllIncomeRecordCountByUid(Map<String, Object> paramMap);

    List<IncomeRecord> selectAllIncomeRecordByDueDate();
}