package com.bjpowernode.mapper.loan;

import com.bjpowernode.model.LoanInfo;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public interface LoanInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int insert(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int insertSelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    LoanInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(LoanInfo record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Tue Jun 11 20:18:04 GMT+08:00 2019
     */
    int updateByPrimaryKey(LoanInfo record);

    /**
     * 查询历史年化收益率
     * @return
     */
    Double selectHistoryAverageRate();

    /**
     * 查询产品信息根据类型
     * @param map
     * @return
     */
    List<LoanInfo> selectLoanInfoByLoanType(Map<String, Object> map);

    /**
     * 查询产品信息数量根据类型
     * @param paramMap
     * @return
     */
    Integer selectLoanInfoCountByLoanType(Map<String, Object> paramMap);
    /**
     * 更新产品表
     * @param loanMap
     * @return
     */
    int updateLoanInfoAfterInvest(HashMap<String, Object> loanMap);
}